# Generated by Django 2.0.5 on 2018-05-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.CharField(blank=True, default='CSB000001', max_length=9, null=True)),
                ('nick_name', models.CharField(default='Untitled', max_length=180)),
                ('given_name', models.CharField(default='Untitled', max_length=180)),
                ('d_o_b', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('location_country', models.CharField(blank=True, choices=[('CAMBODIA', 'cambodia'), ('CHINA', 'china'), ('INDIA', 'india'), ('UGANDA', 'uganda')], max_length=8, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CAM_BIM_RANGSEI_VILLAGE', 'cam_bim_rangsei_village'), ('CAM_BIM_SOKHEM_VILLAGE', 'cam_bim_sokhem_village'), ('CAM_BIM_ARY_VILLAGE', 'cam_bim_ary_village'), ('CAM_SIB_SOKHEM_VILLAGE', 'cam_sib_sokhem_village')], max_length=89, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='child.Child')),
            ],
        ),
    ]
