# Generated by Django 2.0.5 on 2018-05-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='given_name_sir',
        ),
        migrations.AddField(
            model_name='child',
            name='given_name_sur',
            field=models.CharField(default='sur name', max_length=180),
        ),
    ]
