# Generated by Django 2.0.5 on 2018-05-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='given_name',
        ),
        migrations.AddField(
            model_name='child',
            name='given_name_first',
            field=models.CharField(default='first name', max_length=180),
        ),
        migrations.AddField(
            model_name='child',
            name='given_name_sir',
            field=models.CharField(default='sir name', max_length=180),
        ),
        migrations.AlterField(
            model_name='child',
            name='nick_name',
            field=models.CharField(default='nick name', max_length=180),
        ),
    ]
