# Generated by Django 2.0.5 on 2018-05-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='child.Child'),
        ),
        migrations.AlterField(
            model_name='country',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.StaffProfile'),
        ),
    ]
