# Generated by Django 2.0.5 on 2018-05-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_auto_20180523_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fostercare',
            old_name='school',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='healinghome',
            old_name='school',
            new_name='healing_home_id',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='school',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='school',
            new_name='nutr_id',
        ),
        migrations.RenameField(
            model_name='trafficking',
            old_name='school',
            new_name='trfk_program_id',
        ),
    ]
