# Generated by Django 2.0.5 on 2018-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_auto_20180523_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='education_program',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='children', to='child.Education'),
        ),
    ]
