# Generated by Django 2.0.5 on 2018-05-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_auto_20180523_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='child.Child'),
        ),
        migrations.AlterField(
            model_name='country',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='child.Program'),
        ),
        migrations.AlterField(
            model_name='country',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.StaffProfile'),
        ),
    ]
