# Generated by Django 2.0.5 on 2018-05-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_auto_20180523_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='child.Child'),
        ),
    ]
