# Generated by Django 2.0.5 on 2018-05-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20180524_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalupdate',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_update', to='child.Child'),
        ),
    ]
