# Generated by Django 2.0.5 on 2018-05-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_auto_20180523_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='program_number',
            field=models.CharField(blank=True, default='CSB000001', max_length=9, null=True, unique=True),
        ),
    ]
