# Generated by Django 2.0.5 on 2018-05-22 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_you', models.TextField(blank=True, max_length=3000, null=True)),
                ('country_of_residence', models.CharField(blank=True, max_length=120, null=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('location', models.CharField(blank=True, max_length=180, null=True)),
                ('user_language_spoken', models.CharField(blank=True, max_length=120, null=True)),
                ('user_language_spoken_other', models.CharField(blank=True, max_length=120, null=True)),
                ('user_language_written', models.CharField(blank=True, max_length=120, null=True)),
                ('user_language_written_other', models.CharField(blank=True, max_length=120, null=True)),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[('heartbeat_admin', 'Heartbeat Admin (Gives Sitewide Access: Use Caution'), ('manager_cambodia', 'Manager: Cambodia'), ('manager_china', 'Manager: China'), ('manager_india', 'Manager: India'), ('manager_uganda', 'Manager: Uganda'), ('coordinator_cambodia_education', 'Coordinator: Cambodia Education'), ('coordinator_cambodia_education_rangsei', 'Coordinator: Cambodia Education Rangsei Village'), ('coordinator_cambodia_education_sokhem', 'Coordinator: Cambodia Education Sokhem Village'), ('coordinator_cambodia_education_sokhem_sibling', 'Coordinator: Cambodia Education Sokhem Sibling'), ('coordinator_cambodia_education_ary', 'Coordinator: Cambodia Education Ary Village'), ('coordinator_cambodia_foster_care', 'Coordinator: Cambodia Foster Care'), ('coordinator_cambodia_healing_homes', 'Coordinator: Cambodia Healing Homes'), ('coordinator_cambodia_medical', 'Coordinator: Cambodia Medical'), ('coordinator_cambodia_nutrition', 'Coordinator: Cambodia Nutrition'), ('coordinator_cambodia_safe_haven', 'Coordinator: Cambodia Safe Haven')], max_length=424)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
