# Generated by Django 2.0.5 on 2018-05-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='city_of_residience',
            new_name='city_of_residence',
        ),
    ]
