# Generated by Django 2.0.5 on 2018-05-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': (('is_admin', 'Set user as admin'),)},
        ),
    ]
