# Generated by Django 2.0.5 on 2018-05-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='program_country',
            field=models.ManyToManyField(blank=True, related_name='lwb_staff', to='child.Country'),
        ),
    ]
