# Generated by Django 2.0.5 on 2018-05-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180524_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_photo_taken',
            new_name='date_modified',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
